//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public int IdProduct { get; set; }
        public decimal DiscountRate { get; set; }
        public System.DateTime InitialDate { get; set; }
        public System.DateTime FinalDate { get; set; }
    }
}
